micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mn_playground
    username: testuser
    password: testpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true
